- name: Create new GCE instances
  hosts: localhost
  gather_facts: no
  vars:
    names: node1,node2
    type: f1-micro
    image: centos-7
    zone: us-central1-b
  vars_files:
    lamp_simple/group_vars/auth
  tasks:
    - name: Create instances
      local_action:
        module: gce
        instance_names: '{{ names }}'
        machine_type: '{{ type }}'
        image: '{{ image }}'
        zone: '{{ zone }}'
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      register: gce

- name: Open port 80 to allow Apache
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Allow HTTP
      local_action:
        module: gce_net
        name: default
        allowed: tcp:80
        fwname: all-http
